server:
  port: 7771

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  sql:
   init:
      schema-locations: classpath:db/student.sql
      mode: always

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true #该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

secretKey: flyfishflyfish!!